# Generated by Django 3.2.6 on 2021-12-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='follower',
            new_name='conn_follower',
        ),
    ]
